project_id = "eztzddykjnmnpoeyfqcg"

[functions.create-mint-job]
verify_jwt = false

[functions.create-collection]
verify_jwt = false

[functions.update-collection]
verify_jwt = false

[functions.burn-nft]
verify_jwt = false

[functions.delete-collection]
verify_jwt = false