project_id = "eztzddykjnmnpoeyfqcg"

[functions.create-mint-job]
verify_jwt = false

[functions.create-collection]
verify_jwt = false

[functions.mint-collection]
verify_jwt = false

[functions.update-collection]
verify_jwt = false

[functions.burn-nft]
verify_jwt = false

[functions.delete-collection]
verify_jwt = false

[functions.create-boost]
verify_jwt = false

[functions.get-profile]
verify_jwt = false

[functions.set-nickname]
verify_jwt = false

[functions.unlock-pfp]
verify_jwt = false

[functions.set-pfp]
verify_jwt = false

[functions.get-anime-price]
verify_jwt = false