
project_id = "eztzddykjnmnpoeyfqcg"

# Edge functions with JWT verification enabled for security
# Only public read functions and properly secured functions disable JWT verification

[functions.get-mint-fee]
verify_jwt = false  # Public read function

[functions.get-followed-creators]
verify_jwt = false  # Public read function

[functions.create-mint-job]
verify_jwt = true  # Requires authenticated user

[functions.create-collection]
verify_jwt = true  # Requires authenticated user

[functions.mint-collection]
verify_jwt = true  # Requires authenticated user

[functions.update-collection]
verify_jwt = true  # Requires authenticated user

[functions.burn-nft]
verify_jwt = true  # Requires authenticated user

[functions.delete-collection]
verify_jwt = true  # Requires authenticated user

[functions.create-boost]
verify_jwt = true  # Requires authenticated user

[functions.get-profile]
verify_jwt = false  # Public read function

[functions.set-nickname]
verify_jwt = false  # Public function with wallet validation and rate limiting

[functions.unlock-pfp]
verify_jwt = true  # Requires authenticated user and transaction verification

[functions.set-pfp]
verify_jwt = false  # Public function with wallet + ownership validation

[functions.get-anime-price]
verify_jwt = false  # Public read function

[functions.like-nft]
verify_jwt = false  # Public function with wallet validation

[functions.like-collection]
verify_jwt = false  # Public function with wallet validation

[functions.get-liked-nfts]
verify_jwt = false  # Public read function

[functions.get-liked-collections]
verify_jwt = false  # Public read function

[functions.toggle-follow]
verify_jwt = false  # Public function with wallet-signature verification

[functions.upsert-profile]
verify_jwt = true  # Requires authenticated user

[functions.set-bio]
verify_jwt = false  # Public function with wallet validation and rate limiting

[functions.set-banner]
verify_jwt = true  # Requires authenticated user

[functions.export-trading-data]
verify_jwt = true  # Uses Supabase JWT verification
