project_id = "eztzddykjnmnpoeyfqcg"

[functions.get-twitter-stats]
verify_jwt = false

[functions.get-token-holders]
verify_jwt = false

[functions.get-featured-content]
verify_jwt = false

[functions.submit-content]
verify_jwt = false