// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eztzddykjnmnpoeyfqcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6dHpkZHlram5tbnBvZXlmcWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzcwNDIsImV4cCI6MjA3MDgxMzA0Mn0.gr027JXjQ7SE_OOo17VnQSYTIOOQA0iI5JiaqP8J2AA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});